name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run eslint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: CI=true yarn test

  deploy:
    needs: [check]
    runs-on: ubuntu-latest
    env:
      USERNAME: $GITHUB_ACTOR
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Login into registry
        run: docker login docker.pkg.github.com -u $USERNAME -p $GITHUB_TOKEN
      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest .
      - name: Push to registry
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest

  lighthouse:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://hashtag-thu-web.now.sh
          temporaryPublicStorage: true
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: ".lighthouseci"
